CREATE DATABASE DB_ECOMMERCE;

USE DB_ECOMMERCE;

CREATE TABLE TB_FORNECEDOR(
CD_FORNECEDOR INT NOT NULL auto_increment,
NM_FORNECEDOR VARCHAR(255) NOT NULL,
DS_EMAIL VARCHAR(255) NOT NULL,
DS_RAZAO_SOCIAL VARCHAR(255) NOT NULL,
DS_CNPJ VARCHAR(255) NOT NULL,
primary key(CD_FORNECEDOR)
);

CREATE database DB_ECOMMERCE;

USE DB_ECOMMERCE;

CREATE TABLE TB_FORNECEDOR (
	CD_FORNECEDOR INT NOT NULL auto_increment,
	NM_FORNECEDOR VARCHAR(255)NOT NULL,
	DS_MAIL VARCHAR(255) NULL,
	DS_RAZAO_SOCIAL VARCHAR(255)NOT NULL,
	DS_CNPJ VARCHAR(255) NOT NULL,
	primary key(CD_FORNECEDOR)
);

--insert into tb_fornecedor values (1, 'amazon', 'amazon@brasil.com', 'amazon do brazil', '123456789');
--SELECT * FROM db_ecommerce.tb_fornecedor;